// <auto-generated />
using System;
using DTSApi.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DTSApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DTSApi.Entitys.Esquemas", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Secuencia");

                    b.ToTable("Esquemas");
                });

            modelBuilder.Entity("DTSApi.Entitys.Pantallas", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EsquemasSecuencia")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecuenciaEsquemas")
                        .HasColumnType("integer");

                    b.Property<int>("SecuenciaTipoPantalla")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoPantallaSecuencia")
                        .HasColumnType("integer");

                    b.HasKey("Secuencia");

                    b.HasIndex("EsquemasSecuencia");

                    b.HasIndex("TipoPantallaSecuencia");

                    b.ToTable("Pantallas");
                });

            modelBuilder.Entity("DTSApi.Entitys.Permisos", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PermiteEditar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteEjecucion")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteVista")
                        .HasColumnType("boolean");

                    b.HasKey("Secuencia");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("DTSApi.Entitys.Rol", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Secuencia");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("DTSApi.Entitys.RolesEsquema", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EsquemasSecuencia")
                        .HasColumnType("integer");

                    b.Property<int?>("PermisosSecuencia")
                        .HasColumnType("integer");

                    b.Property<int?>("RolSecuencia")
                        .HasColumnType("integer");

                    b.Property<int>("SecuenciaEsquemas")
                        .HasColumnType("integer");

                    b.Property<int>("SecuenciaPermiso")
                        .HasColumnType("integer");

                    b.Property<int>("SecuenciaRol")
                        .HasColumnType("integer");

                    b.HasKey("Secuencia");

                    b.HasIndex("EsquemasSecuencia");

                    b.HasIndex("PermisosSecuencia");

                    b.HasIndex("RolSecuencia");

                    b.ToTable("RolesEsquemas");
                });

            modelBuilder.Entity("DTSApi.Entitys.TipoPantalla", b =>
                {
                    b.Property<int>("Secuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Secuencia");

                    b.ToTable("TipoPantallas");
                });

            modelBuilder.Entity("DTSApi.Entitys.Pantallas", b =>
                {
                    b.HasOne("DTSApi.Entitys.Esquemas", "Esquemas")
                        .WithMany("Pantallas")
                        .HasForeignKey("EsquemasSecuencia");

                    b.HasOne("DTSApi.Entitys.TipoPantalla", "TipoPantalla")
                        .WithMany("Pantallas")
                        .HasForeignKey("TipoPantallaSecuencia");
                });

            modelBuilder.Entity("DTSApi.Entitys.RolesEsquema", b =>
                {
                    b.HasOne("DTSApi.Entitys.Esquemas", "Esquemas")
                        .WithMany("RolesEsquemas")
                        .HasForeignKey("EsquemasSecuencia");

                    b.HasOne("DTSApi.Entitys.Permisos", "Permisos")
                        .WithMany("RolesEsquemas")
                        .HasForeignKey("PermisosSecuencia");

                    b.HasOne("DTSApi.Entitys.Rol", "Rol")
                        .WithMany("RolesEsquemas")
                        .HasForeignKey("RolSecuencia");
                });
#pragma warning restore 612, 618
        }
    }
}
